Numpy Indexing and Selection

In [1]:
import numpy as np

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[3:5]

array([3, 4])

In [8]:
arr[:3]

array([0, 1, 2])

In [9]:
arr[5:]
    

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[1:4] = 45

In [11]:
arr

array([ 0, 45, 45, 45,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr = arr[0:3]

In [26]:
slice_of_arr


array([30, 30, 30])

In [25]:
slice_of_arr [:]= 30

In [27]:
arr

array([30, 30, 30,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr_2d = np.array([[2,4,6],[8,10,12],[14,16,18]])

In [29]:
arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
arr_2d[[0]]

array([[2, 4, 6]])

In [32]:
arr_2d[0][0]

2

In [34]:
arr_2d[2][2]

18

In [35]:
arr_2d[2,1]

16

In [36]:
arr_2d[:2,1:]

array([[ 4,  6],
       [10, 12]])

In [38]:
arr_2d[1:,:2]

array([[ 8, 10],
       [14, 16]])

In [40]:
arr  = np.arange(1,11)

In [41]:
arr >3

array([False, False, False,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [42]:
bool_arr = arr>4

In [43]:
bool_arr


array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [44]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [46]:
arr_2d  =np.arange(50).reshape(5,10)

In [47]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [49]:
arr_2d[2:,6:9]

array([[26, 27, 28],
       [36, 37, 38],
       [46, 47, 48]])