NumPy Array

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
np.ones((1,2))

array([[ 1.,  1.]])

In [24]:
np.linspace(1,2,3)

array([ 1. ,  1.5,  2. ])

In [25]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [30]:
np.random.rand(3,3)

array([[ 0.44202664,  0.40261593,  0.46560181],
       [ 0.68396292,  0.6322407 ,  0.15101512],
       [ 0.3470873 ,  0.85815043,  0.35896246]])

In [28]:
np.random.randn(4,2)

array([[ 0.79701802, -0.28653972],
       [-1.02265158, -0.90489495],
       [-1.65958838, -0.11667356],
       [ 1.55969835,  0.23826143]])

In [34]:
np.random.randint(1,30,5)

array([14, 17,  3, 23, 12])

In [38]:
arr = np.arange(25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
rarr = np.random.randint(0,50,10)

In [43]:
rarr

array([45,  4, 15, 45, 43, 43,  1, 24,  1, 24])

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
rarr.reshape(2,5)

array([[45,  4, 15, 45, 43],
       [43,  1, 24,  1, 24]])

In [46]:
arr.max()

24

In [47]:
arr.min()

0

In [48]:
rarr.argmax()

0

In [49]:
arr = arr.reshape(5,5)

In [53]:
arr.shape

(5, 5)

In [54]:
arr.dtype

dtype('int64')

In [51]:
arr.shape

(5, 5)