## Numpy
Numpy is linear algebra library for python, the reason it is so important for data science with python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one the main building block. NumPy is also incredibly fast, as it has bindings to C libraries. NumPy arrays essentialy  come in two flavous: vector, matrices. 

**Conda install numpy**

**pip install numpy**

In [2]:
import numpy as np

In [44]:
# Creating numpy as array
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(10) # RANDOM SAMPLE FROM UNIFORM DISTRIBUTION

array([0.29455605, 0.93673782, 0.54374104, 0.60136058, 0.06178609,
       0.9349127 , 0.31051506, 0.50527795, 0.05274007, 0.35754387])

In [27]:
np.random.randn(3) # Normal distribution

array([-0.45593661, -1.36322425, -1.27343046])

In [28]:
np.random.randn(3,3)

array([[-1.30792087,  0.70724697, -0.59121558],
       [-0.04407474, -0.72992575, -0.68743331],
       [-0.31776291, -0.78867491, -1.25184438]])

In [30]:
np.random.randint(1,100,10)

array([15, 11, 88, 78, 77, 57, 35, 36, 86, 54])

In [32]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr = np.random.randint(0,50,100)
ranarr

array([ 9, 25, 47, 30, 24, 17,  0, 46,  9, 32, 41, 11, 21, 39,  6, 41, 48,
       10,  1, 42, 20, 20, 25, 48, 18, 13, 12,  7, 45, 47, 38, 38, 34,  5,
       31, 47, 27, 48, 39, 18,  5, 43, 30, 17, 39, 35, 17,  3,  5,  8, 27,
       41, 30, 24, 23, 39, 26, 40,  4, 42, 20, 22, 46, 45, 23,  3, 49,  0,
       18, 14, 31,  7, 44,  2, 47, 27, 38, 18,  9, 47, 16, 21, 43,  0, 16,
       44, 19, 34, 13, 44, 15, 41, 27, 48, 14, 14, 13, 18, 23, 31])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.max(), arr.min(), arr.mean()

(24, 0, 12.0)

In [39]:
arr.argmax(), arr.argmin() # location of max / min

(24, 0)

In [42]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [43]:
arr.dtype

dtype('int64')

### Numpy Indexing and Selection
Indexing starts at 0 in python

In [47]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[5]

5

In [53]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [54]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [56]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [63]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
arr_2d[0][0]

5

In [67]:
arr_2d[0]

array([ 5, 10, 15])

In [68]:
arr_2d[1]

array([20, 25, 30])

In [69]:
arr_2d[1,2]

30

In [70]:
arr_2d[0:,1]

array([10, 25, 40])

In [71]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
bool_arr = arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [73]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [74]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [75]:
 arr[arr<3]

array([1, 2])

In [80]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d[1,3:5]

array([13, 14])

## Numpy operations

* Array with Array
* Array with Scalar
* Universal Array Functions

In [81]:
arr = np.arange(0,11)

In [82]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [85]:
arr * 8

array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

In [86]:
arr + 104

array([104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114])

In [87]:
arr / arr

/home/sudhir/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [89]:
1 / arr

/home/sudhir/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [90]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [91]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [92]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [93]:
np.max(arr)

10

In [94]:
arr.max()

10

In [95]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [96]:
np.log(arr)

/home/sudhir/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

## NumPy Exercise Overview

In [98]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [100]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [102]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [103]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
np.random.rand(1)

array([0.32873013])

In [105]:
np.random.randn(25).reshape(5,5)

array([[-1.36646873, -0.69960978, -0.08129977,  1.35375604,  0.05321783],
       [ 1.79920408,  0.1897395 ,  0.91768313, -0.40247235, -0.40727451],
       [-1.07523091,  1.17604256, -0.57344709,  1.22143153, -1.50589098],
       [-1.34785581,  0.25462438,  0.55581437, -0.98846177, -0.2590466 ],
       [-1.0484871 , -0.69551826,  1.3645847 ,  0.32001963,  0.9044332 ]])

In [107]:
np.arange(0.01,1,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [108]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [110]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [113]:
mat[2:4,1:3]

array([[12, 13],
       [17, 18]])

In [114]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [115]:
mat[3,4]

20

In [116]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [117]:
mat.sum()

325

In [118]:
mat.std()

7.211102550927978

In [119]:
mat.mean()

13.0

In [120]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])